previewsEnabled: true
services:
    plan: free
  - type: web
    name: diamond
    env: 
      - type: python
        PYTHON_VERSION: 3.11
    runtime: python
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    